### ISSUE TITLE
CORS issues when svg sprite is uploaded to CDN

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/svg-sprite-module#110]
My current setup uploads all `_nuxt/` folder content to a CDN for caching reasons, this produces an issue with SVG:

> Unsafe attempt to load URL https://cdn-staging...../eff09c65762d65de737083df265f4fa9.svg from frame with URL https://staging....../. Domains, protocols and ports must match.

Is there any workaround for this issue?

**Comment by farnabaz** [comment]
Specify `publicPath` in the module to load sprites from `/_nuxt/` with the same domain
```
svgSprite: {
    publicPath: '/_nuxt/'
}
```
