### ISSUE TITLE
Custom input/output path brakes building process

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/svg-sprite-module#111]
**How to reproduce:**
Specify the custom path for input/output property, e.g. :
input: ~/static/icons/svg
output: ~/static/icons/gen

**Actual Result:**
Build fails with an error:  

> ~/assets/sprite/gen/sprites.json in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@nuxtjs/svg-sprite/lib/pages/icons-list.vue?vue&type=script&lang=js&

**Expected result:** 
Build should compile successfully

This issue is caused by the fact that the sprite path is hardcoded in icon-list.vue to `~/assets/sprite/gen/sprites.json`. This path should reflect an `output` path instead

**Comment by nassosyian** [comment]
i have the same issue

**Comment by farnabaz** [comment]
Sorry for the late response.
This is a mistake of mine, `icons-list` should've placed at `buildDir` and read output path from module options. I'll fix it ASAP

@nassosyian creating option to disable icons list is not solution for this issue
