### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.../.nuxt/nuxt-svg-sprite-icons-list.vue'

### ISSUE THREAD

**Issue by twxia** [nuxt-community/svg-sprite-module#120]
Hi there,

I'm using SSR mode with express server and I got below error:
```
(node:25166) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.../.nuxt/nuxt-svg-sprite-icons-list.vue' 
```

It can't generate the template correctly in the dev mode, but production mode works really well.

the build process of below code:
```
  if (this.nuxt.options.dev) {
    this.addTemplate({
      src: path.resolve(__dirname, 'pages', 'icons-list.vue'),
      fileName: 'nuxt-svg-sprite-icons-list.vue',
      options
    })
    // register page
    this.nuxt.hook('build:extendRoutes', (routes) => {
      routes.push({
        name: 'icons-list',
        path: options.iconsPath,
        component: path.resolve(this.nuxt.options.buildDir, 'nuxt-svg-sprite-icons-list.vue')
      })
    })
  }
```
should change like this:
```
if (this.nuxt.options.dev) {
    this.addTemplate({
      src: path.resolve(__dirname, 'pages', 'icons-list.vue'),
      fileName: 'nuxt-svg-sprite-icons-list.vue',
      options
    })
    // register page
    this.extendRoutes((routes) => {
      routes.push({
        name: 'icons-list',
        path: options.iconsPath,
        component: path.resolve(this.nuxt.options.buildDir, 'nuxt-svg-sprite-icons-list.vue')
      })
    })
  }
```

**Comment by AndrewBogdanovTSS** [comment]
@twxia have you tried latest 0.4.6 version of the lib? I had similar issue when using custom output directory but now it works fine for me

**Comment by christophstockinger** [comment]
Same issue! Update to latest version are not working!

**Comment by christophstockinger** [comment]
After some attempts I found a working combination:
`"nuxt":"2.10.1"`
`"@nuxtjs/svg-sprite": "^0.4.2"`

**Comment by AndrewBogdanovTSS** [comment]
Interesting. I wonder what was changed after 0.4.2. Is version of Nuxt also makes a difference?

**Comment by christophstockinger** [comment]
Maybe it also works with the latest version of @nuxtjs/svg-sprite. I didn't try it because it works now.
Versions 2.10.0 and 2.10.2 always throw the above error.

This version combination works with and I won't change it currently because there is no need for it

**Comment by twxia** [comment]
My `nuxt` is `2.0.0`. I'm not sure what cause this problem but after I changed some building code, it works again. See this PR, https://github.com/nuxt-community/svg-sprite-module/pull/121

**Comment by farnabaz** [comment]
This should be fixed in version 0.4.7, Thanks to @twxia. Feel free to reopen this issue if Error still exists

**Comment by prochorz** [comment]
I have this error on 0.4.7

**Comment by AleksandrTkach** [comment]
I also have this error on 0.4.7

**Comment by AndrewBogdanovTSS** [comment]
It's strange why am I don't have this issue? Usually it's the other way around 😂
Maybe try to remove your `.nuxt` folder and rerun a deploy?

**Comment by prochorz** [comment]
> It's strange why am I don't have this issue? Usually it's the other way around 😂
> Maybe try to remove your `.nuxt` folder and rerun a deploy?

Are you use express ?

**Comment by prochorz** [comment]
If I move '@nuxtjs/svg-sprite' in nuxt.config.js after 'nuxt-i18n' - it works

**Comment by AleksandrTkach** [comment]
> If I move '@nuxtjs/svg-sprite' in nuxt.config.js after 'nuxt-i18n' - it works

@prochorz  It really helped me, thanks !

**Comment by AndrewBogdanovTSS** [comment]
Yeah, nuxt-i18n uses some dirty tricks for parsing pages available on router so it's always better to put it somewhere higher on the list of plugins. That was one of the reasons I decided to switch to server side i18n which is much simpler and logical

**Comment by stefangrund** [comment]
Same problem here: All generated svg sprites were 404s. After I moved `'@nuxtjs/svg-sprite'` behind `'nuxt-i18n'` thanks to @prochorz' tip everything workes fine.

**Comment by haan123** [comment]
This is happing again
- Nuxt: 2.14.1
- svg-sprite: 0.4.11
- nuxt-i18n: 6.13.7
