### ISSUE TITLE
Omit default namespace when copying icon name of the _icons page

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/svg-sprite-module#123]
Right now when I click on the icon name and copy it to clipboard - I get default namespace also copied so the result is: **icons/icon-name**, which is a bit redundant since **icon-name** will work just fine cos it is located in the root folder anyway so it would be great if namespace was added only for internal folders

**Comment by farnabaz** [comment]
@AndrewBogdanovTSS You're right it's a bit confusing too.

**Comment by AndrewBogdanovTSS** [comment]
@farnabaz any updates?

**Comment by farnabaz** [comment]
@AndrewBogdanovTSS Checkout [v0.4.8](https://github.com/nuxt-community/svg-sprite-module/releases/tag/v0.4.8)
