### ISSUE TITLE
What is a proper way of using this lib in a monorepo?

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/svg-sprite-module#126]
I want to use svg-sprite-module in a monorepo, so icons would reside in it's own independent project that produces a sprite file that can be reused throughout different projects. So I wonder what would be the best way to implement such architecture?
Of course someone could ask me: "Why do you need nuxt dependency in such project at all?" - And maybe would be right, but to me Nuxt is firstly - a great dev UX so I would like to keep using it for a pleasure of comfortable dev UX process even when it's only for the purpose of building icons.

One thing I already understand - I can't rely on the generated <svg-icon> component since the only outcome of the project would be agnostic svg sprite file and all subsequent implementation should happen in a repo that would use this file. So I decided to build an `<svg-icon>` component from scratch. It will look something like this:
```
<template>
  <svg class="svg-icon"
       :class="[{'icon-flipped':flipped}, dir && `svg-icon-${dir}`]"
       :width="size"
       :height="size">
    <use :href="`./icons.svg#i-${name}`" :xlink:href="`./icons.svg#i-${name}`"/>
  </svg>
</template>

<script>
  export default {
    name: 'Icon',
    props: {
      name: {
        type: String,
        required: true
      },
      size: {
        type: [String, Number],
        default: '16'
      },
      dir: {
        type: String
      },
      flipped: {
        type: Boolean,
        default: false
      }
    }
  }
</script>

<style lang="scss">
  .svg-icon {
    flex-shrink: 0;

    &-down {
      transform: rotate(90deg);
    }

    &-up {
      transform: rotate(-90deg);
    }

    &-left {
      transform: rotate(-180deg);
    }
  }
</style>
```
and it's kinda work, my only concern right now is caching - I guess I can't rely on the built in generated file that is placed into a `/_nuxt/` folder but rather add version string to a file that resides in a static folder, something like ./icons.svg?v=1

@farnabaz what do you think about all of this? :) Maybe you could recommend something that can improve such use case?

**Comment by farnabaz** [comment]
@AndrewBogdanovTSS Sorry for the late response, I did not get your whole idea, but I think you can:

1. Create a plugin
2. Pass the project version to your plugin in `nuxt-config`
3. Pass the project version from your plugin to your custom `svg-icon`
4. Prefix version in icon URLs 
`<use :href="`/<% options.version %>/icons.svg#i-${name}`" ... />`
And generate files based on the project version

again I don't really understand your project structure, If you create a sample project, then we can discuss improvements

**Comment by farnabaz** [comment]
Did you resolve the issue?

**Comment by webistomin** [comment]
@farnabaz, maybe you have any ideas how to implement it?

```
packages
  └── app-1
  └── app-2
  └── icons
```

I have two Nuxt.js projects: `app-1`, `app-2`. `.svg` icons are stored in the `icons` folder. How to use the same icons in two projects?

**Comment by AndrewBogdanovTSS** [comment]
@webistomin I haven't solved it entirely, but to answer your question - I would create a sub-repo with icons and linked it with both projects where you need those icons. Once you will make changes in one of the instances of icons repo - you will need to pull changes in every dependant repositories. 
I think you should also be able to just point to an absolute path on your drive with the lib options, that way you will only need to have one icons repo

**Comment by webistomin** [comment]
> I haven't solved it entirely, but to answer your question - I would create a sub-repo with icons and linked it with both projects where you need those icons. Once you will make changes in one of the instances of icons repo - you will need to pull changes in every dependant repositories.
> I think you should also be able to just point to an absolute path on your drive with the lib options, that way you will only need to have one icons repo

@AndrewBogdanovTSS, yeah, thanks. I did exactly as you said.
