### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by MoonCheung** [nuxt-community/svg-sprite-module#129]
This page contains the SVG display that works without refreshing F5, but after you want to refresh F5, the image is shown as follows:
![image](https://user-images.githubusercontent.com/19801190/71589308-65eade00-2b5f-11ea-96b2-6e8d1c5af474.png)

Because the single page in my project introduces the `<svg-icon />` prop name binding to get the value from the calculated property
```javascript
<template>
  <div>
  ...
    <svg-icon :name="osIconName" />
  ...
  </div>
<template>

export.default(){
...
 props: {
    ua: {
      type: String,
      default: ''
    }
 },
 computed:{
  usResult () {
      return usParser(this.ua);
  },
  osIconName() {
      const osName = this.usResult.result.os.name;
      return osName;
   },
  }
...
}
```
How to solve this problem so that I can hit refresh F5 after normal work

**Comment by farnabaz** [comment]
`this.usResult.result.os.name` is `undefined` on ssr load and this cause the problem.

**Comment by MoonCheung** [comment]
Yes, it has something to do with my problem on the project, to fix it can work out, thank you, it has nothing to do with `svg-sprite-module`
