### ISSUE TITLE
[Feature request] Expose an array with icons data for custom list generation

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/svg-sprite-module#135]
Although there is a separate page that is generated for icons, there is no good way of controlling it's behavior, like adding layout, modify the look, etc.
There should be a way to generate such page from scratch based on the icons data. Such data object should be added to Vue instance after icons are generated and be accessible via `this`, something like `this.$svgSptite`
Such list can also be used for other creative purposes like generating icons sets on different pages, etc.

**Comment by farnabaz** [comment]
Providing such a list in Vue instance may cause performance concerns.
In the last version, the module creates a list of icons inside the `output` directory, called `sprites.json`.
By reading this file you can access to the list of icons. This is what the module itself does in the icons list page
