### ISSUE TITLE
How to use svg's original size ?

### ISSUE THREAD

**Issue by gotenxds** [nuxt-community/svg-sprite-module#136]
Hya, thanks for this great lib, I have an issue where I would like to use the original size svg
If I set the width and height to unset or initial the inner svg is in the correct size (the one in the shadow root) but the outer html is much larger

example:

inner svg

![image](https://user-images.githubusercontent.com/3519520/73542456-6cf65c00-443d-11ea-8bfa-89f4443f5300.png)
![image](https://user-images.githubusercontent.com/3519520/73542471-754e9700-443d-11ea-94b3-bc3ed56bcc69.png)

As you can see its in the correct size but if you look at the outer one
![image](https://user-images.githubusercontent.com/3519520/73542504-85667680-443d-11ea-9f6e-0acb9c0471ca.png)
![image](https://user-images.githubusercontent.com/3519520/73542530-92836580-443d-11ea-91ac-e4784f119b35.png)

Is there a way to fix this ?

**Comment by farnabaz** [comment]
As far as I know, you must provide a proper width and height for the icon. The size of the outer SVG can not automatically adjust with shadow root size.

**Comment by DragonWhisperer** [comment]
It works if I copy the viewBox from the inner SVG to the outer SVG, but then I must specify the width OR the height.
