### ISSUE TITLE
How to disable default icons page generation?

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/svg-sprite-module#138]
I would like to disable _icons page since I simply don;t need it anymore. Is there a way to do that?

**Comment by farnabaz** [comment]
@AndrewBogdanovTSS Update to v0.4.9 and pass `false` to `iconsPath`
I've updated options docs

**Comment by AndrewBogdanovTSS** [comment]
Works fine now, thank you
