### ISSUE TITLE
Version on npm differs from github version.

### ISSUE THREAD

**Issue by NicolasReibnitz** [nuxt-community/svg-sprite-module#167]
Hi!

I found an issue with svg-sprite-module that seems to have been fixed in the repo. But the fix does not reflect in the same version on npm. Both versions being v0.4.10.

See here (line 11): [icons-list.vue @ npm.runkit.com](https://npm.runkit.com/@nuxtjs/svg-sprite/lib/pages/icons-list.vue?t=1592175245922)

It still says`:key="symbol"` vs. `:key="symbol.path"` as was fixed in [6cde160](https://github.com/nuxt-community/svg-sprite-module/commit/6cde16043b7c658e95e1a8aadbe6cb33040745d7).

I have no idea how that can happen but I'd be very happy if you could look into this.

Thanks in advance!

**Comment by farnabaz** [comment]
Hi Nicolas
You are right, I've forgotten to publish this fix, I will publish version 0.4.11 later today

**Comment by farnabaz** [comment]
I released [version v0.4.11](https://github.com/nuxt-community/svg-sprite-module/releases/tag/v0.4.11)
Thank you

**Comment by NicolasReibnitz** [comment]
Thanks farnabaz! Truly appreciated.
