### ISSUE TITLE
How to correctly reference sprite

### ISSUE THREAD

**Issue by warheartvik** [nuxt-community/svg-sprite-module#172]
Hello,

I installed this library and tried to do something like the below code, but, referencing sprite in assets folder, does't work for me when v-binding to :xlink:href.  Since it is a nuxt project  what I did was to set the output to the static folder. v-binding to static folder sprite works fine, but I'm not sure if it is the best way to do this.

`
  svgSprite: {
    input: '~/assets/images/icons',
    output: '~/static/sprite'
  },
`

`    

    <svg class="icon__svg">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="~/assets/sprite/gen/icons.svg#i-bold"></use>
    </svg>    

     

    <svg class="icon__svg">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" :xlink:href="'~/assets/sprite/gen/icons.svg#i-bold'"></use>
    </svg>

     

    <svg class="icon__svg">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" :xlink:href="'/sprite/icons.svg#i-add-col-after'"></use>
    </svg>
`

What is the  correct way to reference the sprite in assets folder?

**Comment by farnabaz** [comment]
Hi,
Sorry for the late response, please provide a reproduction project.  
For your issue, for more about input/output refer to [Options doc](https://github.com/nuxt-community/svg-sprite-module#options).

**Comment by farnabaz** [comment]
@warheartvik If you want to use any resources outside of the static directory you should get an asset link by using `require`. Look at https://github.com/nuxt-community/svg-sprite-module/blob/master/lib/plugin.js#L16

```html
<use :href="require('~/assets/svg/sprite/icons.svg') + '#i-' + this.iconName" />
```

**Comment by warheartvik** [comment]
@farnabaz Thank you! That solved it!
