### ISSUE TITLE
How to custom layout ?

### ISSUE THREAD

**Issue by sdailly** [nuxt-community/svg-sprite-module#180]
Hello,

The `default` layout is use for render the page, it is possible to change it into the config ?
I would like use a new layout for show the generated icons.

Thanks

**Comment by sdailly** [comment]
it is possible to add ? 
`const DEFAULTS = {
  input: '~/assets/sprite/svg',
  output: '~/assets/sprite/gen',
  defaultSprite: 'icons',
  svgoConfig: null,
  elementClass: 'icon',
  spriteClassPrefix: 'sprite-',
  publicPath: null,
  iconsPath: '/_icons',
  layout: 'default'
}` in incons-list.vue . 

and `layout: '<%= options.layout %>',` in module.js 

Thnaks a lot :)

**Comment by farnabaz** [comment]
Hey
Defining a layout for the page is not possible at the time, but you can:

- Create a custom page
- Define your layout
- Use modules pages component

```vue
<script>
import Page from '@nuxtjs/svg-sprite/lib/pages/icons-list'
export default {
  ...Page,
  layout: 'custom-layout'
}
</script>

```
