### ISSUE TITLE
Svg files have black spots instead of color

### ISSUE THREAD

**Issue by alexgil1994** [nuxt-community/svg-sprite-module#19]
Hello, thank you to both Nuxt and the creators of the module for providing it as a service for us Vue - Nuxt developers.

I wanted to test it before I start implementing it in personal projects. I used free SVG icons and illustrations found through the sites [drawkit](https://www.drawkit.io/#browse-now-button) (which has some wonderful ones under MIT license) and [flaticon](https://www.flaticon.com/search?word=dog). 

You can see from my testing repository that some of them show black spots instead of their actual color and others (the dog and the hand) look as they should. Is this a problem of the svg files themselves, the svg-sprite-module or have I done something wrong?

I did some farther searching and found that such problems with black spots on svgs occurred in more Github repositories like ( [1](https://github.com/evil-mad/robopaint/issues/275), [2](https://github.com/mpdf/mpdf/issues/450) ) so I guess it might be a generic svg problem?

You can find my testing repo at [nuxt-svg-test](https://github.com/alexgil1994/nuxt-svg-test)

Steps to view the problem :

1). Clone the repo
2). Run `npm install`
3). Run `npm run lint -- --fix`
4). Run `npm run dev`

I installed the module, created the 2 needed folders in assets and imported the svg files. Then, I used them in the index.vue page as you can see after running the project.

Hopefully it isn't something complicating

Thank you for your time

**Comment by farnabaz** [comment]
Sorry for the late response
Should be fixed in next release by (569821c)

**Comment by galvez** [comment]
thanks @farnabaz -- remember running into this as well :)
