### ISSUE TITLE
defaultSprite under nuxt build

### ISSUE THREAD

**Issue by transtone** [nuxt-community/svg-sprite-module#193]
I found it must name the input dir to `icons`, and `nuxt build` (spa, not ssr) will generate a file named `icons.svg`.  
if the dir named `svg`, it will get a `svg.svg` file.

but in dev mode, `nuxt`  can translate dir named `svg` to file `icons.svg`.

![CA0E5E73-3CCA-4b9e-9CFD-D09C8ED74A01](https://user-images.githubusercontent.com/46688/93594046-b8b73f00-f9e7-11ea-8926-2345c93fdbc6.png)

**Comment by farnabaz** [comment]
I don't get your point, what is the issue here?  It would be great if you provide a reproduction sample

**Comment by transtone** [comment]
If name the `svgicons's sub dir` with a different name of `defaultSprit's setting`, it can't build a right svg file in output dir when run `nuxt build`. and the page can't find the svg icons, because of the wrong file name.

**Comment by farnabaz** [comment]
Could you create a reproduction project on GitHub or Codesandbox?

**Comment by transtone** [comment]
> Could you create a reproduction project on GitHub or Codesandbox?

https://github.com/transtone/nuxt-svg-spirit-demo 

please see this demo: 
`yarn dev` is ok,
`yarn build && yarn start` get error.

**Comment by farnabaz** [comment]
When you create a sub-directory with the name `test`, it will creates `test.svg` in the output-dir and you should use `test/` as a prefix in the name of those icons.

`<svg-icon name="test/svg-file-name" />`

take a look at module [usage section](https://github.com/nuxt-community/svg-sprite-module#usage)
