### ISSUE TITLE
Need help with config

### ISSUE THREAD

**Issue by zavvla** [nuxt-community/svg-sprite-module#212]
Hi.
Can you tell me what I'm doing wrong?

I want to take the sources from `~/assets/svg/` and put the generated file in `~/static/svg`
But I encountered a problem:
1 the .gitignore file is Added
2. Not modified\removed the prefix i-
3. Automatically populated width and height

My config:

`svgSprite: {
        input: "~/assets/svg/",
        output: "~/static/svg",
        defaultSprite: "sprite",
        spriteClassPrefix: "",
    }`

In finally i want use 

`
<svg>
      <use xlink:href="~/static/svg/sprite.svg#reload"></use>
</svg>
`
where reload it's symbol's id.
thx

**Comment by zavvla** [comment]
I looked at the code and found that the .gitignore file is added automatically? can I fix this via the pull request + parameter?

**Comment by farnabaz** [comment]
@zavvla We may have an option to disable `.gitignore`. The contribution is more that welcome 👍 
About the others, you may create a custom config for SVGO, see [options sections](https://github.com/nuxt-community/svg-sprite-module#options)
