### ISSUE TITLE
Don't Ignore all files or directories in output directory?

### ISSUE THREAD

**Issue by mtmtkzm** [nuxt-community/svg-sprite-module#22]
Hello,  Thank you for useful nuxt module!

I want to gitignore only file such as `icons.svg` not `*`. 
For example, I set options to `nuxt.config.js` like:

```
svgSprite: {
  input: "~/assets/svg/icons",
  output: "~/assets/svg",
  defaultSprite: "icon-sprite"
}
```

All icon files in `~/assets/svg/icons` will be also ignored because `.gitignore` has `*`.
Only I can do is change directory structure?
thank you

**Comment by farnabaz** [comment]
>  Only I can do is change directory structure?

Yes.
For now, there isn't any option to customize `.gitignore` on project. although we recommend setting the output path inside `.nuxt` directory, for example:   
```
svgSprite: {
  input: "~/assets/svg/icons",
  output: "~/.nuxt/svg",
  defaultSprite: "icon-sprite"
}
```
In next realese, default output path will change to something like this and module will not generate `.gitignore`

**Comment by mtmtkzm** [comment]
@farnabaz 
Thanks for your response.

>   output: "~/.nuxt/svg",

> In next realese, default output path will change to something like this and module will not generate .gitignore

Sound good 👍 Thank you.
