### ISSUE TITLE
clip mask

### ISSUE THREAD

**Issue by badoubadou** [nuxt-community/svg-sprite-module#234]
Hi, 
I'm having an issue with clip mask in svg. It's working on page load, but if you change page then it's not masking any more. 
Is it a know issue ? Thanks !

**Comment by farnabaz** [comment]
Could you provide a reproduction sample using [template.nuxtjs.org](https://template.nuxtjs.org)?

**Comment by badoubadou** [comment]
Hi, I don't really know what was the problem, but I started again from scratch and made it work. sorry for the useless question.
