### ISSUE TITLE
Is it possible to use an icon as a css background-image ?

### ISSUE THREAD

**Issue by existe-deja** [nuxt-community/svg-sprite-module#239]
Hi,

I'm wondering if it's possible, and how if yes, to use an icon incide my css.
For exemple: I have some radio button with an icon and I was wondering if I could use the generated sprite also.

Thanks!

**Comment by bjerh** [comment]
You  can use svg-sprites for backgrounds no problem. Just grab the correct outputted path for the generated SVG-sprite file.

`background-image: url(directory/path-to-svg-sprite.svg#arrow-right);`

**Comment by SergeyMustafin** [comment]
how you made it work?

i did the same rule background-image: url('~static/images/icons/sprite.svg#i-user');

but it not working

**Comment by SergeyMustafin** [comment]
> You can use svg-sprites for backgrounds no problem. Just grab the correct outputted path for the generated SVG-sprite file.
> 
> `background-image: url(directory/path-to-svg-sprite.svg#arrow-right);`

**Comment by existe-deja** [comment]
I think It will be in your assets more than in your static folder

**Comment by SergeyMustafin** [comment]
> I think It will be in your assets more than in your static folder

can you show how you used background-image please? how you made it works?
just some html & css, without codepen and etc
