### ISSUE TITLE
Incompatible with SSR in aws-lambda

### ISSUE THREAD

**Issue by entr** [nuxt-community/svg-sprite-module#24]
Module is making FS write calls during load. `nuxt.render` is failing in Lambda function as it's a read-only environment. Can't we generate sprite and .gitignore files during build phase only?

**Comment by farnabaz** [comment]
It's weird because module generates all files on build and require them on load.

@pi0 any idea on this?

**Comment by entr** [comment]
I think the problem is that [init is called](https://github.com/nuxt-community/svg-sprite-module/blob/v0.2.0/lib/module.js#L24) directly in module entry point and the fact there's a `writeFile()` there. Not sure when and how modules are loaded but my guess is they are being imported during `new Nuxt(config)`.

**Comment by pi0** [comment]
Should be fixed in next release by (4bb045aa867a4803b22a8ad7c29af1fb1379f529)
