### ISSUE TITLE
href links to [hash].svg instead of [folder].svg

### ISSUE THREAD

**Issue by podlebar** [nuxt-community/svg-sprite-module#249]
Hi.. 
i have multiple folders in my svg folder and those sprites are beeing generated fine..

but when i use
`<svg-icon name="ui/logo" class="header__logo-icon" />` i would assume that the href and xlink:href would link to ui.svg. Instead the links are going to: /sprite/144df9f5061d17975a1f61f2f479b5df.svg#i-logo

those files are not generated at all.

my config:
```  
svgSprite: {
    input: '~/assets/svg',
    output: '~/static/sprite',
    publicPath: '/sprite',
    svgoConfig: null
  }
```

how can i avoid those hashed file links?

**Comment by farnabaz** [comment]
Hey,
This module uses [Nuxt Assets System](https://nuxtjs.org/docs/directory-structure/assets/) to load the sprite file and assets serialized by webpack. To avoid this long hashed names and uses meaningful name, we can add name option into [`fileLoaderOptions`](https://github.com/nuxt-community/svg-sprite-module/blob/ae844ec4f02bed5d71d7d8139dee4ce833267422/src/module.ts#L124)

```js
const fileLoaderOptions: any = {
   name: 'sprite/[name].[contenthash:6].[ext]'
}
```

**Comment by podlebar** [comment]
hi.. well this does not help.. if i use the default settings the linked file still contains hashes but the generated files don't.. so the component is than still linking to a file that does not exist.

I really don't min if there is a has or not.. the problem ist that no matter what configuration i make the generated files do not exist only the not hashes ones that the component does not link to.
