### ISSUE TITLE
Nuxt 3 support status

### ISSUE THREAD

**Issue by vaiil** [nuxt-community/svg-sprite-module#257]
It seems that module doesn't support nuxt 3. 
Do you have any plans to start supporting it? 
It will be great to add note about current status of supporting to readme.

**Comment by SergeyMustafin** [comment]
Any updates? Ty

**Comment by cdowning** [comment]
Any update on this?

**Comment by Durasel18** [comment]
god bless

**Comment by larsvdd** [comment]
Still nothing?

**Comment by AnatoliiDev** [comment]
Any update on this?

**Comment by igamov** [comment]
Analog https://github.com/nuxt-modules/icon

**Comment by snowdream** [comment]
Any  release for Nuxt 3？

**Comment by ewilan-riviere** [comment]
If some people are ready to test a similar module for Nuxt 3, I work on [nuxt-svg-transformer](https://github.com/kiwilan/nuxt-svg-transformer). I would like to have as much feedback as possible.

**Comment by FarhanShares** [comment]
@ewilan-riviere [nuxt-svg-transformer](https://github.com/kiwilan/nuxt-svg-transformer) looks cool. I'm going to try it.

**Comment by FarhanShares** [comment]
@ewilan-riviere [nuxt-svg-transformer](https://github.com/kiwilan/nuxt-svg-transformer) looks cool. I'm going to try it.

**Comment by DulcePC** [comment]
Since there is no news, I will use this [nuxt-icon](https://nuxt.com/modules/icons)

**Comment by bmulholland** [comment]
I think this is resolved now: https://github.com/nuxt-community/svg-sprite-module/releases/tag/v1.0.0

**Comment by farnabaz** [comment]
It's been long, but finally v1.0.0 supports Nuxt 3 and uses SVGO 3.
Feel free to open issues or drop PRs if you see any issues or place for improvements 🍻
