### ISSUE TITLE
Use Nuxt resolver

### ISSUE THREAD

**Issue by manniL** [nuxt-community/svg-sprite-module#3]
Hey 👋 

I suggest to use the nuxt resolver for resolving paths
https://github.com/nuxt-community/svg-sprite-module/blob/b07a0621a1368ff48fcb33759a8825688cdaf21d/lib/module.js#L17

Example: https://github.com/nuxt-community/style-resources-module/blob/master/lib/module.js#L31

**Comment by pi0** [comment]
The resolver needs the directory to exist to be resolved which in this case is not. (Output dir) We have to support an option in nuxt to allow directory resolves. But still is a breaking change for older nuxt users.

**Comment by manniL** [comment]
Whoops, good point there 👍
