### ISSUE TITLE
Not supported in Node v10? import path from 'path'

### ISSUE THREAD

**Issue by 555ea** [nuxt-community/svg-sprite-module#32]
So I have an error
```
@nuxtjs\svg-sprite\lib\module.js:1
  (function (exports, require, module, __filename, __dirname) { import path from 'path'
                                                                       ^^^^
  SyntaxError: Unexpected identifier
```
AFAIK es6 imports are not enabled by default, are we supposed to run with experimental features flag ? I can't use this sprite generator, my Nuxt app renders with Error Cannot GET /

**Comment by AndrewBogdanovTSS** [comment]
@555ea es6 imports are not enabled by default even in Node 13, but it's working fine for me, tested it with Node 10, 12, 13. Besides, Nuxt uses babel transpilation in both server and client. Are you sure you are using the module correctly?
