### ISSUE TITLE
How to set svgo plugin options

### ISSUE THREAD

**Issue by ReginnaChao** [nuxt-community/svg-sprite-module#38]
I want to use variables css on transform like `<path transform="var(--transform)" d="..."/>`, but get NaN path for attribute `d`.

I think that the probable cause is svgo plugin settings "convertTransform".
Is there any option to set it?

SVG File
![image](https://user-images.githubusercontent.com/19789757/58950676-e9a73c80-87c1-11e9-8b92-c88cb041dfc9.png)

Output
![image](https://user-images.githubusercontent.com/19789757/58950627-d09e8b80-87c1-11e9-940a-13b2c1211f6b.png)

**Comment by ahmedfaical** [comment]
+1 i need the same thing too

**Comment by larzon83** [comment]
+1
Could you please make SVGO options/plugins configurable? Some plugins are used in the svg.js (see screen), but I need more. You could look here how it can be implemented: https://github.com/egoist/svg-to-vue-component/blob/master/loader.js

**Comment by farnabaz** [comment]
🎉  In v0.4.1 options/plugins are configurable 🎉
