### ISSUE TITLE
Defs inside symbols

### ISSUE THREAD

**Issue by or2e** [nuxt-community/svg-sprite-module#4]
Hola!

If you have an svg icon like this:

`<svg width="126" height="47" xmlns="http://www.w3.org/2000/svg">
<defs>
  <linearGradient x1=".258%" y1="49.75%" x2="101.258%" y2="49.75%" id="a">
    <stop stop-color="#E94E8E" offset="0%"/>
    <stop stop-color="#30AA93" offset="21.532%"/>
    <stop stop-color="#312783" offset="43.368%"/>
    <stop stop-color="#F39CBF" offset="63.182%"/>
    <stop stop-color="#2A99C5" offset="80.568%"/>
    <stop stop-color="#6DCCD1" offset="100%"/>
  </linearGradient>
</defs>
  <path d="M66.465 260.939c18.853 0 20.853 37.706 39.706 37.706s20.853-37.706 39.706-37.706 18.853 37.706 37.706 37.706" transform="translate(-62 -256)" stroke="url(#a)" stroke-width="8" fill="none" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`

The generated svg :

`<svg xmlns="http://www.w3.org/2000/svg" id="i-wave1" width="100%" height="100%"><path d="M66.465 260.939c18.853 0 20.853 37.706 39.706 37.706s20.853-37.706 39.706-37.706 18.853 37.706 37.706 37.706" transform="translate(-62 -256)" stroke="url(#wave1-a)" stroke-width="8" fill="none" stroke-linecap="round" stroke-linejoin="round"></path></svg>`

Module cuts defs.

Thanks!

**Comment by farnabaz** [comment]
Hi, Thanks for the report 
Looks like this is relative to [Chromium/Webkit bug](https://code.google.com/p/chromium/issues/detail?id=109212):

>Issue 109212: SVG (filter | fill | stroke | clip-path | mask) from external files not applied
>
> What steps will reproduce the problem?
> Define a filter in an SVG file, assign it an ID.
> Embed some SVG in an HTML file.
> Use the CSS directive `filter: url(file#id)` to reference the filter in the SVG file.
> What is the expected result? The filter should be applied.
> What happens instead? No filter is applied.

Although bug still exists in Firefox, That will fix in next release

**Comment by llavre** [comment]
Hello, folks!

Seems this issue still exists in 0.21 module version even with first comment example (https://github.com/nuxt-community/svg-sprite-module/issues/4#issue-407510401).

Gradient which is defined in svg defs are still cutted in Chrome (75.0.3770.100).

**Comment by farnabaz** [comment]
Hi @llavre,
As I said above this is a known issue of chromium, and we couldn't do anything about it for now
