### ISSUE TITLE
generated SVG sprite in not optimized

### ISSUE THREAD

**Issue by ahmedfaical** [nuxt-community/svg-sprite-module#40]
Hello, the svg sprite generated is not optimized

**Comment by farnabaz** [comment]
Sorry for the late response, could you make an example?

**Comment by AndrewBogdanovTSS** [comment]
@ahmedfaical you can further optimize generated sprite by providing custom config object for SVGO:
```
svgSprite: {
    svgoConfig: {
       // https://github.com/nuxt-community/svg-sprite-module/blob/master/docs/svgo-config.md
    }
  }
```
