### ISSUE TITLE
svg icons do not work in ie11

### ISSUE THREAD

**Issue by mosstly-design** [nuxt-community/svg-sprite-module#42]
The icons do not show up in IE11.

**Comment by jpsc** [comment]
Hello @mosstly-design,

It does not work ie11 has problems with svg sprites.
If you want it to work you should find a way to include in you project this https://github.com/jonathantneal/svg4everybody

Hope it helps.

**Comment by gafuri** [comment]
I solved using svg4everybody. A bit dirty, at least it works.

In nuxt.config.js:
```
plugins: [
    { src: '~plugins/svg4everybody.js', ssr: false }
]
```

~plugins/svg4everybody.js:
```
import svg4everybody from 'svg4everybody'
svg4everybody()
```
Shame on MS. We spending lot of hours just to make it work in IE (Edge).

**Comment by jpsc** [comment]
I'm glad it helped :)

**Comment by weifeiyue** [comment]
[https://github.com/Keyamoon/svgxuse](https://github.com/Keyamoon/svgxuse) is better
