### ISSUE TITLE
Remove unused svg items

### ISSUE THREAD

**Issue by jpsc** [nuxt-community/svg-sprite-module#44]
It would be interesting if the generated sprite only included the icons that are actually beeing used. 

Now everything you add to the folder gets automatically added to the sprite.

**Comment by farnabaz** [comment]
I don't think it will possible. First, it requires processing codes in the build time so the module could extract used icons. Second, what we should do with dynamic icons? (`<svg-icon :name="x" />`)

The only feasible way is generating sprites on the fly, but this solution will cause performance issues.

**Comment by jpsc** [comment]
Sounds fair. I think it's a fair compromise if you just create a directory for all the items and then another where you just pull the ones you want to use.
