### ISSUE TITLE
Allow setting of a global class to the `svg-icon` element

### ISSUE THREAD

**Issue by bernardocorbella** [nuxt-community/svg-sprite-module#53]
I was thinking it could probably be useful to receive `class` as a prop and add it to the `svg-icon` component so we can style it globally.

Currently, the first solution I see is to wrap `svg-icon` into another component (ie `<foo-icon>`) and use it in every template. However, I believe this could be solved trivially.

I'd like to propose some API that allows this to be set on initialisation:

```js
svgSprite: {
    input: '~/assets/sprite/svg',
    output: '~/assets/sprite/gen',
    defaultSprite: 'icons',
    elementClass: 'icon'
  }
```

This will allow the icons to share a global style and we already have the generated `id` for individual style.

I came across this problem when (naively) styling the `svg` element globally which led to weird behaviours when scaling

Do you consider this is worth it? Maybe I'm missing some obvious solution.

**Comment by farnabaz** [comment]
> I was thinking it could probably be useful to receive `class` as a prop and add it to the `svg-icon` component so we can style it globally.

Right now you can do this, just add `class="foo"`, [DEMO](https://codesandbox.io/s/nuxtjssvg-sprite-2qxxj)

```
<svg-icon name="tets" class="icon" />
```

I believe default class will help, I'll consider it in future, but for now you can use `class` attr
