### ISSUE TITLE
Generated SVG sprite is not compatible with IE11

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/svg-sprite-module#86]
It would be great if SVG files were analyzed and optimized by a webpack plugin before inserted into app.html file

**Comment by farnabaz** [comment]
IE does not support SVG Sprite.  
SEE https://github.com/nuxt-community/svg-sprite-module/issues/42#issuecomment-504453377

I am closing this issue, but feel free to reopening this if you have any question
