### ISSUE TITLE
Do not modify app.html file if no changes occur

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/svg-sprite-module#87]
app.html is modified by every run of `nuxt` command even though no icons are changed in the resources. This is very irritating since file is not a gitignore list and it always needs to be reverted before the commit

**Comment by farnabaz** [comment]
I don't understand, the module does not change `app.html` in any case.  
Could you create a simple project to reproduce this issue?

**Comment by AndrewBogdanovTSS** [comment]
@farnabaz it modifies line endings. Have you tried in on Windows? I will try to prepare a test project

**Comment by AndrewBogdanovTSS** [comment]
That's what I get after every run of the project in the dev mode 
https://take.ms/1fbJ4
https://take.ms/1lKw4

**Comment by farnabaz** [comment]
I believe this isn't related to `svg-sprite-module`. It is sound like your IDE modifies line endings.

**Comment by AndrewBogdanovTSS** [comment]
No, it happens even if I run my project outside of any IDE. Change is tracked by Git. It also can be proved by looking in the terminal, where `✔ success SVG sprite injected` message appear every time, even if no modifications to icons has been applied
