### ISSUE TITLE
Allow injection of SVG sprite per page

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/svg-sprite-module#88]
It's not always efficient to inject whole SVG sprite at body level. Sometimes we need certain icons only on certain pages so it would be better if there was an opportunity to split icons into multiple sprites and include them at different pages or layouts

**Comment by farnabaz** [comment]
Using module you can split icons into multiple sprites, simply create a directory inside the input directory and place your icons in it. checkout module [usage](https://github.com/nuxt-community/svg-sprite-module#usage)  

Although module injects sprites that used on the page, so if you do not load an icon from a sprite, it does not inject to in the page
