### ISSUE TITLE
SVG breaks

### ISSUE THREAD

**Issue by siegy22** [nuxt-community/svg-sprite-module#92]
I have this strange behaviour that my SVGs break using this module:
https://codesandbox.io/s/nuxtjssvg-sprite-v2g8t

Here's the difference of the original vs the one in the sprite:
https://gist.github.com/siegy22/921a710b177cea739337787b6747cf92

May this be an issue with the optimizer?

**Comment by farnabaz** [comment]
Actually, this behavior is pretty expected, this is relative to a well-known bug of chromium

https://github.com/nuxt-community/svg-sprite-module/issues/4#issuecomment-461388976

Try codesandbox at Firefox  
If you remove gradients from SVG icons, everything works fine in chrome too

**Comment by siegy22** [comment]
@farnabaz But then it's a problem with the optimizer, right? Because as you can see, the original works in chrome as well.

Can I configure the optimizer to not make our SVGs break?

**Comment by farnabaz** [comment]
No, the optimizer works fine. This is chromium issue with external files
